# Site settings
title: Tales from the Locker
subtitle: Yet another tech blog
author: Sergey Chebykin
email: sergey.chebykin@gmail.com
twitter_username: good_soul
github_username:  dr-nafanya
permalink: pretty

# Exclude site build infrastructure
exclude: [node_modules, styl, package.json, gulpfile.js .gitignore]