# Site settings
title: A Locker with Tales
author: Sergey Chebykin
email: sergey.chebykin@gmail.com
description: Yet another blog. A tech blog... sometimes
twitter_username: good_soul
github_username:  dr-nafanya
permalink: pretty

# Exclude site build infrastructure
exclude: [node_modules, styl, package.json, gulpfile.js .gitignore]